# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d66395ce1357a102765f0c5868fee6f1862cc38693aee78fea8e5d47584cb2ccd8f5a84c8f7c702decaab246703d13f6194510c1929b556bc558d19c5823e591

test:
  secret_key_base: be204fcb67f05d1b5cf750e9c3eeec3726e50af9a221255fb89859fca84cdc81d1fb778b0712d990b6dacbe4e70c48f21dbce10d6d960ebce57e87841a1d9907

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
